import struct

PAYLOAD_FORMAT = "!Iq3f4ffq"
PAYLOAD_STRUCT = struct.Struct(PAYLOAD_FORMAT)
PAYLOAD_SIZE = PAYLOAD_STRUCT.size
SEQUENCE_OFFSET = 0
TEXTURE_ID_OFFSET = PAYLOAD_SIZE - 8
DISCOVERY_REQUEST = b"NETWORKYEE_HAPTIC_DISCOVER_V1"
DISCOVERY_RESPONSE_PREFIX = "NETWORKYEE_HAPTIC_HERE "
SUMMARY_RESPONSE_PREFIX = "NETWORKYEE_HAPTIC_SUMMARY "
